version: "3"
services:
  node-1:
    container_name: node-1
    image: selenium/node-docker:4.14.1-20231020
    volumes:
      - /Users/cmlim/Desktop/node.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5555:5555"  # 추가: 호스트의 5555 포트를 컨테이너의 5555 포트로 매핑

  selenium-hub:
    image: selenium/hub:4.14.1-20231020
    container_name: selenium-hub
    environment:
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_SESSION_REQUEST_TIMEOUT=30
      - SE_SESSION_RETRY_INTERVAL=5
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
