# node1.toml
[server]
port = 5555

[node]
detect-drivers = false

[relay]
url = "http://localhost:4723"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Androis\", \"appium:platformVersion\": \"12\", \"appium:deviceName\": \"LM-G820N\", \"appium:automationName\": \"UiAutomator2\"}"
]